---
- name: Sysconfig playbook
  hosts: all
  become: yes
  tasks:
    - name: install backup pkg
      yum:
        name: linuxacademy_backup_package
        state: present
      ignore_errors: true
    - name: RH specific item
      lineinfile:
        path: /root/addresses
        line: "{{ ansible_facts['all_ipv4_addresses'] }}"
        create: yes
      when: ansible_facts['os_family'] == 'RedHat'

- name: config webservers
  hosts: webservers
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: create and populate index.html
      lineinfile:
        path: /var/www/html/index.html
        line: Waiting for content.
        create: yes
        owner: apache
        group: apache
        mode: 0644

- name: config dbservers
  hosts: dbservers
  become: yes
  tasks:
    - name: create dba user
      user:
        name: dba
        state: present
    - name: add user content
      copy:
        src: /root/DBAstuff.txt
        dest: /home/dba/DBAstuff.txt

- name: config git
  hosts: webservers:dbservers
  become: yes
  tasks:
    - name: install git
      yum:
        name: git
        state: present
